version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    groups:
      patch:
        update-types:
          - patch
          - minor
    schedule:
      interval: monthly

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      patch:
        update-types:
          - patch
          - minor
    schedule:
      interval: "monthly"
