import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { build, dev } from "astro";
import { parseHtml, readPage } from "../../packages/starlight-agent-docs/src/convert.ts";

const root = fileURLToPath(new URL("../fixtures/site/", import.meta.url));

test("static exports support base paths and both Astro output formats", async () => {
    const directory = await mkdtemp(join(tmpdir(), "starlight-agent-docs-"));
    const environment = process.env.NODE_ENV;
    process.env.NODE_ENV = "production";
    try {
        for (const format of ["directory", "file"] as const) {
            const outDir = join(directory, format);
            await build({ root, outDir, base: "/docs/", trailingSlash: "never", build: { format }, logLevel: "error" });
            const html = await readFile(join(outDir, format === "file" ? "guide.html" : "guide/index.html"), "utf8");
            const page = readPage(parseHtml(html));
            assert.ok(page);
            const path = format === "file" ? "/docs/guide.md" : "/docs/guide/index.md";
            assert.equal(page.markdownPath, path);
            assert.ok(html.includes(`href="${path}"`));
            assert.ok(html.includes("data-original-edit-link"));
            assert.ok(html.includes("data-agent-docs-link"));
            assert.ok(html.includes('name="fixture-metadata"'));
            assert.ok(html.includes('rel="describedby" href="/docs/llms.txt"'));
            const markdown = await readFile(join(outDir, path.slice("/docs/".length)), "utf8");
            assert.match(markdown, /Applications MUST preserve/);
            const index = await readFile(join(outDir, "llms.txt"), "utf8");
            assert.ok(index.includes(`https://example.com${path}`));
            assert.match(index, /## Guides/);
            assert.match(index, /## Guides[\s\S]*## More guides[\s\S]*Autogenerated example/);
            assert.doesNotMatch(index, /Unpublished draft/);
            assert.ok(index.includes("/docs/index.md"));
            const homepage = await readFile(join(outDir, "index.html"), "utf8");
            assert.ok(!homepage.includes("data-agent-docs-link"));
            assert.ok(homepage.includes('rel="alternate" type="text/markdown"'));
            assert.match(await readFile(join(outDir, "index.md"), "utf8"), /Fixture homepage/);
        }
    } finally {
        await rm(directory, { recursive: true, force: true });
        if (environment === undefined) delete process.env.NODE_ENV;
        else process.env.NODE_ENV = environment;
    }
});

test("development exports include drafts and respond to content edits", async () => {
    const environment = process.env.NODE_ENV;
    process.env.NODE_ENV = "development";
    const server = await dev({ root, base: "/docs/", server: { host: "127.0.0.1", port: 0 }, logLevel: "error" });
    const origin = `http://127.0.0.1:${server.address.port}`;
    const guide = join(root, "src/content/docs/guide.md");
    const original = await readFile(guide, "utf8");
    try {
        for (const path of ["/docs/index.md", "/docs/guide/index.md", "/docs/draft/index.md", "/docs/llms.txt"]) {
            const response = await fetch(origin + path);
            assert.equal(response.status, 200, path);
            const content = await response.text();
            assert.ok(content.length > 0);
            if (path.endsWith(".md")) assert.match(response.headers.get("content-type") ?? "", /^text\/markdown/);
            const head = await fetch(origin + path, { method: "HEAD" });
            assert.equal(head.status, 200, path);
            assert.equal(await head.text(), "");
        }
        const index = await (await fetch(`${origin}/docs/llms.txt`)).text();
        assert.match(index, /Unpublished draft/);
        assert.match(index, /## Guides[\s\S]*## More guides[\s\S]*Autogenerated example/);
        assert.equal((await fetch(`${origin}/docs/missing/index.md`)).status, 404);
        await writeFile(guide, `${original}\nFreshly updated guidance.\n`);
        const deadline = Date.now() + 10_000;
        let updated = "";
        do {
            await new Promise((resolve) => setTimeout(resolve, 100));
            updated = await (await fetch(`${origin}/docs/guide/index.md`)).text();
        } while (!updated.includes("Freshly updated guidance.") && Date.now() < deadline);
        assert.match(updated, /Freshly updated guidance\./);
    } finally {
        await writeFile(guide, original);
        await server.stop();
        if (environment === undefined) delete process.env.NODE_ENV;
        else process.env.NODE_ENV = environment;
    }
});
